# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: cp -a functions/ dist/
      - run: yarn build:app
      - run: yarn export:app
  deploy:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
      - run: cp package.json dist/functions && cp package-lock.json dist/functions
      - run: mkdir pages
      - run: yarn firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build-deploy:
    triggers:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build